---
clone:
  git:
    image: quay.io/packet/drone-git
    tags: true

pipeline:
  build_image_ubuntu_test_env_image:
    image: docker
    commands:
      - docker build -t image-ubuntu-test-env --build-arg packet_api_token="$PACKET_API_TOKEN" --build-arg packer_deploy_key="$PACKER_DEPLOY_KEY" tools/packet-packer/ci
      - mkdir build
      - touch build/image-ubuntu-test-env
      - ln -s ../7 build/7
      - ln -s ../8 build/8
      - ln -s ../testing build/testing
      - ln -s ../tools build/tools
    secrets:
      - packet_api_token
      - packet_project
      - packer_deploy_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  packer_validate_templates:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - ./tools/packet-packer/scripts/template-validate 7/templates
      - ./tools/packet-packer/scripts/template-validate 8/templates

  packer_centos8_t1small:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - mkdir -p build/packer_centos8_t1small
      - cd build/packer_centos8_t1small
      - ln -s ../../scripts scripts; ln -s ../../tools tools; ln -s ../../tools/packet-packer packet-packer
      - packer build -var 'plan=t1.small.x86' -var 'fac=sjc1' -var 'os=centos_7' -var 'mode=install' ../8/templates/centos-8.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
